apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  annotations:
    metallb.universe.tf/allow-shared-ip: "sharing key"
spec:
  selector:
    app: grafana
  type: LoadBalancer
  loadBalancerIP: 192.168.99.182
  ports:
  - port: 3000
    name: graf-svc-port
    targetPort: graf-cont-port
    protocol: TCP
    nodePort: 3000

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deploy
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: image_grafana
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
          name: graf-cont-port
